server:
  port: 8999

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: USER-SERVICES
          uri: lb://USER-SERVICES
          predicates:
            - Path=/user/**
        - id: CONTACT-SERVICES
          uri: lb://CONTACT-SERVICES
          predicates:
            - Path=/contact/**